

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sv" suppressHydrationWarning>
      <body>
  <div
    style={{
      minHeight: "100vh",
      background: "#fafafa",
      display: "flex",
      justifyContent: "center",
      padding: "40px 16px",
    }}
  >
    <div
      style={{
        width: "100%",
        maxWidth: "720px",
        background: "#fff",
        padding: "32px",
        borderRadius: "12px",
        boxShadow: "0 10px 30px rgba(0,0,0,0.05)",
      }}
    >
      {children}
    </div>
  </div>
</body>
    </html>
  );
}
